name: Cache and Install npm
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      shell: bash
      run: npm install
