name: Build and Publish Package
runs:
  using: composite
  steps:
    - name: Cache and Install npm
      uses: ./.github/actions/cache-and-install-npm
    - name: Build Package
      run: npm run build:packages
    - name: Publish Package
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
