name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  package-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/cache-and-install-npm
      - name: Package JSON
        run: npm run sort-package-json:check

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/cache-and-install-npm
      - name: Prettier
        run: npm run prettier:check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/cache-and-install-npm
      - name: Lint
        run: npm run lint

  unused-exports:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/cache-and-install-npm
      - name: Unused Exports
        run: npm run unused-exports
